FROM python:3.9

# Установка необходимых зависимостей
RUN pip install Flask mysql-connector-python
# Установка рабочей директории
WORKDIR /app

# Копирование файлов приложения
COPY main.py /app/

# Запуск приложения
CMD ["python", "main.py"]
