version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    networks:
      backend:
        ipv4_address: 172.20.0.5
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=example

  db:
    image: mysql:8
    networks:
      backend:
        ipv4_address: 172.20.0.10
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=example
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - db_data:/var/lib/mysql

  db-client:
    image: mysql:8
    command: ["sh", "-c", "sleep 10 && mysql -hdb -uroot -proot_password example -e 'show databases; use example; show tables; SELECT * from requests LIMIT 10;'"]
    depends_on:
      - db
    networks:
      backend:
        aliases:
          - db-client
    restart: "no"

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  db_data:
